// <auto-generated />
using System;
using Apeyai.Persistence.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apeyai.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20210710152116_RenameSchemaAndAttributeTables")]
    partial class RenameSchemaAndAttributeTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.BaseAttributeDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SchemaId");

                    b.HasIndex("Name", "SchemaId")
                        .IsUnique()
                        .HasDatabaseName("IX_UniqueAttributeNameAmongSchemaConstraint");

                    b.ToTable("Attribute");

                    b.HasDiscriminator<string>("Type").HasValue("BaseAttributeDbEntity");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.SchemaDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Schema");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.ForeignSchemaReferenceAttributeDbEntity", b =>
                {
                    b.HasBaseType("Apeyai.Persistence.Sqlite.DbEntities.BaseAttributeDbEntity");

                    b.Property<string>("ForeignSchemaName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SchemaDbEntityId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SchemaDbEntityId");

                    b.ToTable("Attribute");

                    b.HasDiscriminator().HasValue("ForeignSchemaReferenceAttributeDbEntity");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.TextAttributeDbEntity", b =>
                {
                    b.HasBaseType("Apeyai.Persistence.Sqlite.DbEntities.BaseAttributeDbEntity");

                    b.Property<int>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SchemaDbEntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TextAttributeDbEntity_SchemaDbEntityId");

                    b.HasIndex("SchemaDbEntityId");

                    b.ToTable("Attribute");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.BaseAttributeDbEntity", b =>
                {
                    b.HasOne("Apeyai.Persistence.Sqlite.DbEntities.SchemaDbEntity", "Schema")
                        .WithMany("Attributes")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.ForeignSchemaReferenceAttributeDbEntity", b =>
                {
                    b.HasOne("Apeyai.Persistence.Sqlite.DbEntities.SchemaDbEntity", null)
                        .WithMany("ForeignSchemaReferenceAttributes")
                        .HasForeignKey("SchemaDbEntityId");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.TextAttributeDbEntity", b =>
                {
                    b.HasOne("Apeyai.Persistence.Sqlite.DbEntities.SchemaDbEntity", null)
                        .WithMany("TextAttributes")
                        .HasForeignKey("SchemaDbEntityId");
                });

            modelBuilder.Entity("Apeyai.Persistence.Sqlite.DbEntities.SchemaDbEntity", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("ForeignSchemaReferenceAttributes");

                    b.Navigation("TextAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
